# Generated by Django 5.1.4 on 2024-12-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
    ]
