# Generated by Django 5.1.4 on 2024-12-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_doctor_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
