# Generated by Django 5.1.4 on 2024-12-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_doctor_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='patient',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
