# Generated by Django 5.1.4 on 2024-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='desription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
