# Generated by Django 5.1.4 on 2024-12-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_doctor_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='desription',
            new_name='description',
        ),
    ]
